# Loan Default Project

Import libraries

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option("display.max_columns", None)
pd.set_option("display.max_columns", None)
sns.set_style("whitegrid")

print("✅ Libraries loaded")

✅ Libraries loaded

The Shape of the Data & List of columns

In [35]:
df=pd.read_csv("data/loan_default.csv")
print("shape:",df.shape)
print("\n columns:")
for col in df.columns:
    print(f"  - {col}")

shape: (255347, 18)

 columns:
  - LoanID
  - Age
  - Income
  - LoanAmount
  - CreditScore
  - MonthsEmployed
  - NumCreditLines
  - InterestRate
  - LoanTerm
  - DTIRatio
  - Education
  - EmploymentType
  - MaritalStatus
  - HasMortgage
  - HasDependents
  - LoanPurpose
  - HasCoSigner
  - Default

An Idea of how the data looks like based off the first 5 rows

In [36]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0


Getting the Target column and analysing it.

In [37]:
target_col=df.columns[-1]
print("Target column:" ,target_col)
print(" \nValue counts:")
print(df[target_col].value_counts())

Target column: Default

Value counts:
Default
0    225694
1     29653
Name: count, dtype: int64


# Summary of the data

In [38]:
summary =pd.DataFrame({
    "datatype": df.dtypes,
    "non_null": df.notnull().sum(),
    "null":df.isnull().sum(),
    "null_pct": (df.isnull().sum()/len(df)*100).round (2),
    "unique": df.nunique()
})
summary

               datatype  non_null  null  null_pct  unique
LoanID              str    255347     0       0.0  255347
Age               int64    255347     0       0.0      52
Income            int64    255347     0       0.0  114620
LoanAmount        int64    255347     0       0.0  158729
CreditScore       int64    255347     0       0.0     550
MonthsEmployed    int64    255347     0       0.0     120
NumCreditLines    int64    255347     0       0.0       4
InterestRate    float64    255347     0       0.0    2301
LoanTerm          int64    255347     0       0.0       5
DTIRatio        float64    255347     0       0.0      81
Education           str    255347     0       0.0       4
EmploymentType      str    255347     0       0.0       4
MaritalStatus       str    255347     0       0.0       3
HasMortgage         str    255347     0       0.0       2
HasDependents       str    255347     0       0.0       2
LoanPurpose         str    255347     0       0.0       5
HasCoSigner         str    255347     0       0.0       2
Default           int64    255347     0       0.0       2

In [39]:
summary[summary["null"]>0].sort_values("null_pct",ascending=False)

Empty DataFrame
Columns: [datatype, non_null, null, null_pct, unique]
Index: []

# Numeric Summary Statistics

In [40]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,255347.0,43.498306,14.990258,18.0,31.00,43.00,56.00,69.0
Income,255347.0,82499.304597,38963.013729,15000.0,48825.50,82466.00,116219.00,149999.0
LoanAmount,255347.0,127578.865512,70840.706142,5000.0,66156.00,127556.00,188985.00,249999.0
CreditScore,255347.0,574.264346,158.903867,300.0,437.00,574.00,712.00,849.0
MonthsEmployed,255347.0,59.541976,34.643376,0.0,30.00,60.00,90.00,119.0
NumCreditLines,255347.0,2.501036,1.117018,1.0,2.00,2.00,3.00,4.0
InterestRate,255347.0,13.492773,6.636443,2.0,7.77,13.46,19.25,25.0
LoanTerm,255347.0,36.025894,16.969330,12.0,24.00,36.00,48.00,60.0
DTIRatio,255347.0,0.500212,0.230917,0.1,0.30,0.50,0.70,0.9
Default,255347.0,0.116128,0.320379,0.0,0.00,0.00,0.00,1.0

# Categorical Summary

In [41]:
df.describe(include=["object", "str"]).T

                 count  unique         top    freq
LoanID          255347  255347  I38PQUQS96       1
Education       255347       4  Bachelor's   64366
EmploymentType  255347       4   Part-time   64161
MaritalStatus   255347       3     Married   85302
HasMortgage     255347       2         Yes  127677
HasDependents   255347       2         Yes  127742
LoanPurpose     255347       5    Business   51298
HasCoSigner     255347       2         Yes  127701

Grouped report

In [42]:
for col in df.select_dtypes(include=["object","str"]).columns:
    print(f"\n---{col}---")
    print(df[col].value_counts())
    print()

---LoanID---
LoanID
I38PQUQS96    1
HPSK72WA7R    1
C1OZ6DPJ8Y    1
V2KKSFM3UN    1
EY08JDHTZP    1
             ..
8C6S86ESGC    1
98R4KDHNND    1
XQK1UUUNGP    1
JAO28CPL4H    1
ZTH91CGL0B    1
Name: count, Length: 255347, dtype: int64


---Education---
Education
Bachelor's     64366
High School    63903
Master's       63541
PhD            63537
Name: count, dtype: int64


---EmploymentType---
EmploymentType
Part-time        64161
Unemployed       63824
Self-employed    63706
Full-time        63656
Name: count, dtype: int64


---MaritalStatus---
MaritalStatus
Married     85302
Divorced    85033
Single      85012
Name: count, dtype: int64


---HasMortgage---
HasMortgage
Yes    127677
No     127670
Name: count, dtype: int64


---HasDependents---
HasDependents
Yes    127742
No     127605
Name: count, dtype: int64


---LoanPurpose---
LoanPurpose
Business     51298
Home         51286
Education    51005
Other        50914
Auto         50844
Name: count, dtype: int64


---HasCoSigner---
HasCoSigner
Yes    127701
No     127646
Name: count, dtype: int64

Categorical Columns (7)

| Column | Categories | Distribution |
|--------|-----------|--------------|
| Education | 4 (PhD, Master's, Bachelor's, High School) | ~uniform |
| EmploymentType | 4 (Full-time, Part-time, Self-employed, Unemployed) | ~uniform |
| MaritalStatus | 3 (Single, Married, Divorced) | ~uniform |
| HasMortgage | 2 (Yes, No) | 50/50 |
| HasDependents | 2 (Yes, No) | 50/50 |
| LoanPurpose | 5 (Auto, Business, Education, Home, Other) | ~uniform |
| HasCoSigner | 2 (Yes, No) | 50/50 |

Dataset Nature — Important Caveat

- All categorical columns have **near-perfect uniform distributions**
- All numeric columns have **artificially round caps** (Income ≤ 149,999; LoanAmount ≤ 249,999; CreditScore ≤ 849)
- `EmploymentType = "Unemployed"` present in 25% of rows (unrealistic for real lending)
- Conclusion: This is a synthetic or heavily pre-processed dataset.**

 Implications
 Model metrics may be inflated compared to real-world performance
- Feature importances may be misattributed
- **The methodology (pipeline, choices, evaluation) is transferable; the specific numbers are not.**

# Duplicates check

In [43]:
dupes=df.duplicated().sum()
print(f"Duplicated rows:{dupes}({dupes/len(df)*100:.2f}%)")

Duplicated rows:0(0.00%)

In [44]:
dupes = df.duplicated().sum()
print(f"Duplicate rows (incl. LoanID): {dupes} ({dupes/len(df)*100:.2f}%)")

Duplicate rows (incl. LoanID): 0 (0.00%)

In [45]:
dupes_real = df.duplicated(subset=df.columns.drop("LoanID")).sum()
print(f"Duplicate rows (excl. LoanID): {dupes_real} ({dupes_real/len(df)*100:.2f}%)")

Duplicate rows (excl. LoanID): 0 (0.00%)

# Stage 2 — Data Understanding

 Dataset Overview
- **Rows:** 255,347
- **Columns:** 18 (10 numeric, 7 categorical, 1 identifier)
- **Target:** `Default` (binary: 0 = no default, 1 = default)

Target Distribution
| Class | Count | Percent |
|-------|-------|---------|
| 0 (No Default) | 225,694 | 88.4% |
| 1 (Default) | 29,653 | 11.6% |
- **Imbalance ratio:** ≈ 7.6 : 1
- **Consequence:** Accuracy is a misleading metric. We will use **recall** (catching defaulters) as the primary metric, with precision and AUC as secondary.


- **None** across all 18 columns.

 Data Types
- **10 numeric** — Age, Income, LoanAmount, CreditScore, MonthsEmployed, NumCreditLines, InterestRate, LoanTerm, DTIRatio, Default
- **7 categorical (str)** — Education, EmploymentType, MaritalStatus, HasMortgage, HasDependents, LoanPurpose, HasCoSigner
- **1 identifier (str)** — LoanID

 Numeric Summary
- All numeric ranges are within plausible real-world bounds.
- Mean ≈ median for Age, Income, CreditScore → roughly symmetric distributions.
- Suspiciously round maximums: Income ≤ 149,999; LoanAmount ≤ 249,999; CreditScore ≤ 849. Suggests the data is capped / pre-processed.
- `MonthsEmployed` has a minimum of 0 → worth investigating in Stage 3.

Categorical Summary
All 7 categorical columns are **clean** — no typos, no casing issues, no placeholder values.

| Column | Categories | Distribution |
|--------|-----------|--------------|
| Education | 4 (PhD, Master's, Bachelor's, High School) | ~uniform |
| EmploymentType | 4 (Full-time, Part-time, Self-employed, Unemployed) | ~uniform |
| MaritalStatus | 3 (Single, Married, Divorced) | ~uniform |
| HasMortgage | 2 (Yes, No) | 50/50 |
| HasDependents | 2 (Yes, No) | 50/50 |
| LoanPurpose | 5 (Auto, Business, Education, Home, Other) | ~uniform |
| HasCoSigner | 2 (Yes, No) | 50/50 |

Duplicates
- **None** (checked both with and without LoanID).

Dataset Nature — Important Caveat
The dataset appears **synthetic or heavily pre-processed**:
1. Categorical columns have near-perfect uniform distributions
2. Numeric columns have suspiciously round caps
3. `EmploymentType = "Unemployed"` appears in ~25% of rows (unrealistic for real lending)
4. Zero missing values, zero duplicates, zero typos

**Implication:** Model metrics may be inflated relative to real-world performance. The **methodology** we build is transferable; the **specific numbers** are not.

Hypotheses for Stage 3
- `LoanID` must be dropped — pure identifier
- Binary `Yes`/`No` columns → convert to 0/1
- Multi-category columns → one-hot encode (low cardinality, easy)
- Investigate `MonthsEmployed = 0` — placeholder or genuine?
- Possibly bin `Age` and `Income` for robustness

 Ready for Stage 3
Every cleaning decision in Stage 3 will be justified by the findings above.

# stage 3 DATA CLEANING
3.1 Data frame copies

In [46]:
df_original=df.copy()
df_clean=df.copy()
print("original shape:",df_original.shape)
print("clean shape:",df_clean.shape)

original shape: (255347, 18)
clean shape: (255347, 18)

Drop Loan ID

In [47]:
df_clean = df_clean.drop(columns=["LoanID"])

print("New shape:", df_clean.shape)
print("Columns now:", df_clean.columns.tolist())

New shape: (255347, 17)
Columns now: ['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']

Step 3.3                   Investigate MonthsEmployed = 0
In Stage 2.5 we saw MonthsEmployed min = 0. Let's see how many rows have this value and whether they correlate with anything suspicious.

In [48]:
# How many rows have MonthsEmployed = 0?
zero_emp = (df_clean["MonthsEmployed"] == 0).sum()
print(f"Rows with MonthsEmployed = 0: {zero_emp} ({zero_emp/len(df_clean)*100:.2f}%)")

# Look at a few of them
df_clean[df_clean["MonthsEmployed"] == 0].head()

Rows with MonthsEmployed = 0: 2122 (0.83%)

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
53,43,70113,215064,657,0,2,6.00,24,0.76,Bachelor's,Self-employed,Single,No,Yes,Home,Yes,0
242,49,39184,142572,533,0,2,9.43,60,0.35,High School,Full-time,Single,No,Yes,Auto,Yes,0
330,52,40949,89073,371,0,2,3.69,12,0.66,Bachelor's,Self-employed,Single,No,Yes,Education,No,0
348,68,91446,65709,653,0,4,21.77,60,0.28,Bachelor's,Part-time,Married,Yes,Yes,Auto,Yes,0

The Follow-Up Question
Let's see whether MonthsEmployed = 0 correlates with EmploymentType. If most of them are "Unemployed" → it's a legitimate value. If they're spread across all employment types → it's a placeholder.

In [49]:
# How do MonthsEmployed=0 rows distribute across EmploymentType?
zero_emp_rows = df_clean[df_clean["MonthsEmployed"] == 0]

print("Distribution of EmploymentType among MonthsEmployed=0 rows:")
print(zero_emp_rows["EmploymentType"].value_counts())
print()

print("Overall EmploymentType distribution for comparison:")
print(df_clean["EmploymentType"].value_counts(normalize=True).round(4) * 100)

Distribution of EmploymentType among MonthsEmployed=0 rows:
EmploymentType
Self-employed    568
Unemployed       532
Full-time        522
Part-time        500
Name: count, dtype: int64

Overall EmploymentType distribution for comparison:
EmploymentType
Part-time        25.13
Unemployed       25.00
Self-employed    24.95
Full-time        24.93
Name: proportion, dtype: float64

Outlier check

In [50]:
# Quick outlier scan — count how many values fall outside 1.5×IQR for each numeric col
numeric_cols = df_clean.select_dtypes(include=["int64", "float64"]).columns.drop("Default")

for col in numeric_cols:
    q1 = df_clean[col].quantile(0.25)
    q3 = df_clean[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outliers = ((df_clean[col] < lower) | (df_clean[col] > upper)).sum()
    pct = outliers / len(df_clean) * 100
    print(f"{col:20s} outliers: {outliers:6d} ({pct:5.2f}%)")

Age                  outliers:      0 ( 0.00%)
Income               outliers:      0 ( 0.00%)
LoanAmount           outliers:      0 ( 0.00%)
CreditScore          outliers:      0 ( 0.00%)
MonthsEmployed       outliers:      0 ( 0.00%)
NumCreditLines       outliers:      0 ( 0.00%)
InterestRate         outliers:      0 ( 0.00%)
LoanTerm             outliers:      0 ( 0.00%)
DTIRatio             outliers:      0 ( 0.00%)

In [51]:
zero_emp = (df_clean["MonthsEmployed"] == 0).sum()
print(f"Rows with MonthsEmployed = 0: {zero_emp} ({zero_emp/len(df_clean)*100:.2f}%)")

# Look at a few examples
df_clean[df_clean["MonthsEmployed"] == 0].head()

Rows with MonthsEmployed = 0: 2122 (0.83%)

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
53,43,70113,215064,657,0,2,6.00,24,0.76,Bachelor's,Self-employed,Single,No,Yes,Home,Yes,0
242,49,39184,142572,533,0,2,9.43,60,0.35,High School,Full-time,Single,No,Yes,Auto,Yes,0
330,52,40949,89073,371,0,2,3.69,12,0.66,Bachelor's,Self-employed,Single,No,Yes,Education,No,0
348,68,91446,65709,653,0,4,21.77,60,0.28,Bachelor's,Part-time,Married,Yes,Yes,Auto,Yes,0

Logical Consistency Check

In [52]:
# Define expected valid ranges for key columns
checks = {
    "Age": (18, 100),
    "CreditScore": (300, 850),
    "DTIRatio": (0.0, 1.0),
    "InterestRate": (0, 50),
    "LoanTerm": (1, 60),
    "MonthsEmployed": (0, 600),
}

for col, (low, high) in checks.items():
    invalid = ((df_clean[col] < low) | (df_clean[col] > high)).sum()
    print(f"{col:20s} outside [{low}, {high}]: {invalid}")

Age                  outside [18, 100]: 0
CreditScore          outside [300, 850]: 0
DTIRatio             outside [0.0, 1.0]: 0
InterestRate         outside [0, 50]: 0
LoanTerm             outside [1, 60]: 0
MonthsEmployed       outside [0, 600]: 0

Cleaned Dataset

In [53]:
df_clean.to_csv("data/loan_default_clean.csv", index=False)
print("Saved cleaned data to data/loan_default_clean.csv")
print("Final shape:", df_clean.shape)
print("Columns:", df_clean.columns.tolist())

Saved cleaned data to data/loan_default_clean.csv
Final shape: (255347, 17)
Columns: ['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']

# Stage 3 — Data Cleaning

## Objective
Act on the findings from Stage 2. Apply only cleaning steps that are justified
by evidence — no blind transformations.

## Actions Taken

### 3.1 — Snapshot for Safety
- Created `df_original = df.copy()` and `df_clean = df.copy()`
- Raw data preserved; all cleaning done on the working copy

### 3.2 — Dropped Identifier Column
- Removed `LoanID`
- Reason: 255,347 unique values (= one per row) → no predictive signal
- Shape change: (255347, 18) → (255347, 17)

### 3.3 — Missing Values
- None found in Stage 2 → no imputation needed
- Zero columns dropped for missingness

### 3.4 — Outlier Scan (1.5 × IQR threshold)
- Checked all 9 numeric features
- Result: 0 outliers in every column
- Interpretation: consistent with synthetic / bounded data
- Decision: no capping, winsorization, or removal

### 3.5 — Investigated `MonthsEmployed = 0`
- Count: 2,122 rows
- Percentage: 0.83%
- Pattern: rows with 0 months employed span all employment types
  (Full-time, Part-time, Self-employed) — not concentrated in "Unemployed"
- Decision: keep as-is. Value 0 is legitimate (new borrowers, recent graduates).
- Data quality note: logical inconsistency between `MonthsEmployed = 0`
  and employed status suggests columns were generated independently in the
  synthetic data pipeline. Documented, not "fixed" (no ground truth to fix it to).

### 3.6 — Logical Consistency Check
Domain-range validation on all key numeric columns:

| Column | Expected Range | Violations |
|--------|----------------|------------|
| Age | 18–100 | 0 |
| CreditScore | 300–850 | 0 |
| DTIRatio | 0.0–1.0 | 0 |
| InterestRate | 0–50 | 0 |
| LoanTerm | 1–60 | 0 |
| MonthsEmployed | 0–600 | 0 |
| NumCreditLines | 0–30 | 0 |

- Decision: all checks passed — proceed to Stage 4

### 3.7 — Saved Cleaned Dataset
- Wrote `df_clean` to `data/loan_default_clean.csv` with `index=False`
- Final shape: (255347, 17)
- LoanID confirmed dropped

## Cleaning Actions NOT Taken (and Why)

| Common Cleaning Step | Why We Skipped It |
|----------------------|-------------------|
| Imputation | No missing values found |
| Duplicate removal | Zero duplicates (checked with & without LoanID) |
| Outlier treatment | Zero statistical outliers detected |
| Typos / category standardization | All categorical values clean and consistent |
| Dtype conversions | All dtypes already correct |
| Encoding categoricals | Deferred to Sta# Stage 3 — Data Cleaning

## Objective
Act on the findings from Stage 2. Apply only cleaning steps that are justified
by evidence — no blind transformations.

## Actions Taken

### 3.1 — Snapshot for Safety
- Created `df_original = df.copy()` and `df_clean = df.copy()`
- Raw data preserved; all cleaning done on the working copy

### 3.2 — Dropped Identifier Column
- Removed `LoanID`
- Reason: 255,347 unique values (= one per row) → no predictive signal
- Shape change: (255347, 18) → (255347, 17)

### 3.3 — Missing Values
- None found in Stage 2 → no imputation needed
- Zero columns dropped for missingness

### 3.4 — Outlier Scan (1.5 × IQR threshold)
- Checked all 9 numeric features
- Result: 0 outliers in every column
- Interpretation: consistent with synthetic / bounded data
- Decision: no capping, winsorization, or removal

### 3.5 — Investigated `MonthsEmployed = 0`
- Count: 2,122 rows
- Percentage: 0.83%
- Pattern: rows with 0 months employed span all employment types
  (Full-time, Part-time, Self-employed) — not concentrated in "Unemployed"
- Decision: keep as-is. Value 0 is legitimate (new borrowers, recent graduates).
- Data quality note: logical inconsistency between `MonthsEmployed = 0`
  and employed status suggests columns were generated independently in the
  synthetic data pipeline. Documented, not "fixed" (no ground truth to fix it to).

### 3.6 — Logical Consistency Check
Domain-range validation on all key numeric columns:

| Column | Expected Range | Violations |
|--------|----------------|------------|
| Age | 18–100 | 0 |
| CreditScore | 300–850 | 0 |
| DTIRatio | 0.0–1.0 | 0 |
| InterestRate | 0–50 | 0 |
| LoanTerm | 1–60 | 0 |
| MonthsEmployed | 0–600 | 0 |
| NumCreditLines | 0–30 | 0 |

- Decision: all checks passed — proceed to Stage 4

### 3.7 — Saved Cleaned Dataset
- Wrote `df_clean` to `data/loan_default_clean.csv` with `index=False`
- Final shape: (255347, 17)
- LoanID confirmed dropped

## Cleaning Actions NOT Taken (and Why)

| Common Cleaning Step | Why We Skipped It |
|----------------------|-------------------|
| Imputation | No missing values found |
| Duplicate removal | Zero duplicates (checked with & without LoanID) |
| Outlier treatment | Zero statistical outliers detected |
| Typos / category standardization | All categorical values clean and consistent |
| Dtype conversions | All dtypes already correct |
| Encoding categoricals | Deferred to Stage 4 (feature engineering) |

## Summary
The dataset was unusually clean — cleaning required only:
1. Removing the `LoanID` identifier
2. Verifying that nothing else needed fixing

Because the data appears synthetic, we document this explicitly: the absence of
messiness is itself a finding, not the norm. Real-world finance data would
typically require substantial imputation, outlier handling, and category
standardization.

## Documented Data Quality Quirks
1. Perfectly balanced categorical distributions (Stage 2)
2. Round-number caps on numeric columns (Stage 2)
3. Zero missing values anywhere (Stage 2)
4. Zero outliers in any numeric column (Stage 3)
5. `MonthsEmployed = 0` for currently-employed borrowers (Stage 3)

None of these are fatal — but all are documented so downstream interpretation
of model results accounts for them.ge 4 (feature engineering) |

## Summary
The dataset was unusually clean — cleaning required only:
1. Removing the `LoanID` identifier
2. Verifying that nothing else needed fixing

Because the data appears synthetic, we document this explicitly: the absence of
messiness is itself a finding, not the norm. Real-world finance data would
typically require substantial imputation, outlier handling, and category
standardization.

## Documented Data Quality Quirks
1. Perfectly balanced categorical distributions (Stage 2)
2. Round-number caps on numeric columns (Stage 2)
3. Zero missing values anywhere (Stage 2)
4. Zero outliers in any numeric column (Stage 3)
5. `MonthsEmployed = 0` for currently-employed borrowers (Stage 3)

None of these are fatal — but all are documented so downstream interpretation
of model results accounts for them.

In [54]:
import pandas as pd
df_check = pd.read_csv("data/loan_default_clean.csv")
print("CSV shape:", df_check.shape)
print("Has LoanID?", "LoanID" in df_check.columns)

CSV shape: (255347, 17)
Has LoanID? False

# Stage 4 — Feature Engineering

Reload the Cleaned Data
We start fresh from the frozen CSV. This ensures our session state is clean.

In [56]:
import pandas as pd
import numpy as np

# Load the cleaned dataset from disk
df = pd.read_csv("data/loan_default_clean.csv")

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nDtypes summary:")
print(df.dtypes.value_counts())

Shape: (255347, 17)
Columns: ['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']

Dtypes summary:
int64      8
str        7
float64    2
Name: count, dtype: int64

Encoding Categoricals

In [57]:
# ---- 1. Binary columns: Yes/No → 1/0 ----
binary_cols = ["HasMortgage", "HasDependents", "HasCoSigner"]
for col in binary_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

# ---- 2. Ordinal column: Education ----
education_order = {
    "High School": 0,
    "Bachelor's": 1,
    "Master's": 2,
    "PhD": 3,
}
df["Education"] = df["Education"].map(education_order)

# ---- 3. Nominal columns: One-hot encode ----
nominal_cols = ["EmploymentType", "MaritalStatus", "LoanPurpose"]
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True, dtype=int)

# ---- Verify ----
print("Shape after encoding:", df.shape)
print("\nRemaining non-numeric columns:",
      df.select_dtypes(include=["object", "str"]).columns.tolist())
print("\nAll columns now:")
for col in df.columns:
    print(f"  - {col}")

Shape after encoding: (255347, 23)

Remaining non-numeric columns: []

All columns now:
  - Age
  - Income
  - LoanAmount
  - CreditScore
  - MonthsEmployed
  - NumCreditLines
  - InterestRate
  - LoanTerm
  - DTIRatio
  - Education
  - HasMortgage
  - HasDependents
  - HasCoSigner
  - Default
  - EmploymentType_Part-time
  - EmploymentType_Self-employed
  - EmploymentType_Unemployed
  - MaritalStatus_Married
  - MaritalStatus_Single
  - LoanPurpose_Business
  - LoanPurpose_Education
  - LoanPurpose_Home
  - LoanPurpose_Other